/*
 * This source file was generated by the Gradle 'init' task
 */
package knitpix;

import org.junit.jupiter.api.Test;

import knitpix.app.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should exist");
    }
}
